[LEDConfigHybris]
 
# Choose Vanilla backend
BackEnd=vanilla

# Configure base directories for red/green/blue channels
RedDirectory=/sys/class/leds/red
GreenDirectory=/sys/class/leds/green
BlueDirectory=/sys/class/leds/blue

RedBrightnessFile=/sys/class/leds/red/brightness
RedMaxBrightnessFile=/sys/class/leds/red/max_brightness
RedBlinkDelayOnFile=/sys/class/leds/red/pause_hi
RedBlinkDelayOffFile=/sys/class/leds/red/pause_lo
RedBlinkFile=/sys/class/leds/red/blink

GreenBrightnessFile=/sys/class/leds/green/brightness
GreenMaxBrightnessFile=/sys/class/leds/green/max_brightness 
GreenBlinkDelayOnFile=/sys/class/leds/green/pause_hi       
GreenBlinkDelayOffFile=/sys/class/leds/green/pause_lo        
GreenBlinkFile=/sys/class/leds/green/blink 

BlueBrightnessFile=/sys/class/leds/blue/brightness
BlueMaxBrightnessFile=/sys/class/leds/blue/max_brightness 
BlueBlinkDelayOnFile=/sys/class/leds/blue/pause_hi       
BlueBlinkDelayOffFile=/sys/class/leds/blue/pause_lo        
BlueBlinkFile=/sys/class/leds/blue/blink 
